dataset:
  root: "/home/zqh/workspace/animedataset"
  style: "Hayao"
  batch_size: 8
  num_workers: 32
  data_mean: [-4.4346957, -8.665916, 13.100612]
  augment: False
  normalize: True
  totenor: True
checkpoint:
  # monitor: "loss"
  save_top_k: -1
  mode: "all"
logger:
  save_dir: "logs"
  name: "animegan_pre"
  version: null
model:
  lr_g: 0.0002
  b1: 0.5
  b2: 0.99
  generator_name: AnimeGenerator
  discriminator_name: AnimeDiscriminator
  pretrained_name: VGGCaffePreTrained
trainer:
  gpus: 1
  max_epochs: 2
  benchmark: True
  deterministic: True
  log_every_n_steps: 10
  val_check_interval: 500
  limit_val_batches: 1
# make train CODE=scripts/animegan_pretrain.py CFG=configs/animegan_pretrain.yaml
# make tensorboard LOGDIR=logs/animegan_pre/
